language: cpp

compiler:
  - clang
  - gcc

before_install:
  - "sudo apt-get -y build-dep libsdl libsdl-image"
  - "wget http://www.libsdl.org/release/SDL2-2.0.1.tar.gz"
  - "tar xfz SDL2-2.0.1.tar.gz"
  - "cd SDL2-2.0.1"
  - "./configure"
  - "make"
  - "sudo make install"
  - "cd .."
  - "wget http://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.0.tar.gz"
  - "tar xfz SDL2_image-2.0.0.tar.gz"
  - "cd SDL2_image-2.0.0"
  - "./configure"
  - "make"
  - "sudo make install"
  - "cd .."

before_script:
  - "cmake ."

script: "make test"
